version: "3.8"
services:
  api:
    container_name: job-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    command: turbo run start --filter=api
    ports:
      - 4000:4000
    restart: unless-stopped
  web:
    container_name: job-web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    command: turbo run start --filter=web
    ports:
      - 8002:3000
    restart: unless-stopped
