version: "3.8"
services:
  db:
    container_name: job-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cv-applications-tracking
      POSTGRES_HOST_AUTH_METHOD: trust
    hostname: db
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    container_name: job-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    command: turbo run start --filter=api
    ports:
      - 4000:4000
    restart: unless-stopped
  web:
    container_name: job-web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    command: turbo run start --filter=web
    ports:
      - 8002:3000
    restart: unless-stopped
volumes:
  db-data:
