import type { Metadata } from 'next'

import ApolloWrapper from '@/lib/apollo/apollo-wrapper'
import { ReactNode } from 'react'

import '../../styles/globals.css'
import { Providers } from './provider'

export const metadata: Metadata = {
  description: 'Generated by create turbo',
  title: 'Create Turborepo',
}

interface Props {
  children: ReactNode
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={'h-svh'}>
        <ApolloWrapper>
          <Providers>{children}</Providers>
        </ApolloWrapper>
      </body>
    </html>
  )
}
