import '../../styles/globals.css'
import type { Metadata } from "next";
import ApolloWrapper from "@/lib/apollo/apollo-wrapper";
import {Providers} from "./provider";
import {ReactNode} from "react";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

interface Props {
  children: ReactNode;
}

export default function RootLayout({children}: Props) {
  return (
    <html lang="en">
      <body className={"h-svh"}>
        <ApolloWrapper>
          <Providers>
            {children}
          </Providers>
          </ApolloWrapper>
      </body>
    </html>
  );
}
